export const data = [
  {
    name: "Organization 1",
    acronym: "ORG1",
    type: "Type 1",
    website: "www.example.com/1",
  },
  {
    name: "Organization 2",
    acronym: "ORG2",
    type: "Type 2",
    website: "www.example.com/2",
  },
  {
    name: "Organization 3",
    acronym: "ORG3",
    type: "Type 3",
    website: "www.example.com/3",
  },
  {
    name: "Organization 4",
    acronym: "ORG4",
    type: "Type 4",
    website: "www.example.com/4",
  },
  {
    name: "Organization 5",
    acronym: "ORG5",
    type: "Type 5",
    website: "www.example.com/5",
  },
  {
    name: "Organization 6",
    acronym: "ORG6",
    type: "Type 6",
    website: "www.example.com/6",
  },
  {
    name: "Organization 7",
    acronym: "ORG7",
    type: "Type 7",
    website: "www.example.com/7",
  },
  {
    name: "Organization 8",
    acronym: "ORG8",
    type: "Type 8",
    website: "www.example.com/8",
  },
  {
    name: "Organization 9",
    acronym: "ORG9",
    type: "Type 9",
    website: "www.example.com/9",
  },
  {
    name: "Organization 10",
    acronym: "ORG10",
    type: "Type 10",
    website: "www.example.com/10",
  },
  {
    name: "Organization 10",
    acronym: "ORG10",
    type: "Type 10",
    website: "www.example.com/10",
  },
  {
    name: "Organization 10",
    acronym: "ORG10",
    type: "Type 10",
    website: "www.example.com/10",
  },
  {
    name: "Organization 10",
    acronym: "ORG10",
    type: "Type 10",
    website: "www.example.com/10",
  },
];

export const dataStaff = [
  {
    id: 1,
    person: "John Doe",
    jobTitle: "Software Engineer",
    organization: "XYZ Inc",
    departmentunit: "Engineering",
    facility: "Headquarters",
    email: "john.doe@example.com",
  },
  {
    id: 2,
    person: "Jane Smith",
    jobTitle: "Product Manager",
    organization: "ABC Corp",
    departmentunit: "Product Development",
    facility: "Branch Office",
    email: "jane.smith@example.com",
  },
  {
    id: 3,
    person: "Bob Johnson",
    jobTitle: "Data Analyst",
    organization: "Data Co.",
    departmentunit: "Data Science",
    facility: "Remote",
    email: "bob.johnson@example.com",
  },
  {
    id: 4,
    person: "Alice Brown",
    jobTitle: "Graphic Designer",
    organization: "Design Studio",
    departmentunit: "Design",
    facility: "Studio Office",
    email: "alice.brown@example.com",
  },
  {
    id: 5,
    person: "Charlie Davis",
    jobTitle: "Sales Representative",
    organization: "Sales Inc.",
    departmentunit: "Sales",
    facility: "Main Office",
    email: "charlie.davis@example.com",
  },
  {
    id: 6,
    person: "Eva Wilson",
    jobTitle: "HR Manager",
    organization: "HR Solutions",
    departmentunit: "Human Resources",
    facility: "Corporate Office",
    email: "eva.wilson@example.com",
  },
  {
    id: 7,
    person: "David Lee",
    jobTitle: "Financial Analyst",
    organization: "Finance Group",
    departmentunit: "Finance",
    facility: "Headquarters",
    email: "david.lee@example.com",
  },
  {
    id: 8,
    person: "Grace White",
    jobTitle: "Marketing Specialist",
    organization: "Marketing Co.",
    departmentunit: "Marketing",
    facility: "Marketing Office",
    email: "grace.white@example.com",
  },
  {
    id: 9,
    person: "Frank Miller",
    jobTitle: "Customer Support",
    organization: "Support Inc.",
    departmentunit: "Customer Support",
    facility: "Support Center",
    email: "frank.miller@example.com",
  },
  {
    id: 10,
    person: "Olivia Turner",
    jobTitle: "Accountant",
    organization: "Accounting Firm",
    departmentunit: "Accounting",
    facility: "Corporate Office",
    email: "olivia.turner@example.com",
  },
  // Add more data entries as needed
];
